checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - "tests/"
build:
    environment:
        php: '5.5.0'
    dependencies:
        before:
            - composer install
            - mysql -uroot -e "create database IF NOT EXISTS meetme;"
            - mysql -uroot -e "CREATE USER 'meetme'@'localhost' IDENTIFIED BY 'Lj5Fvj8K';"
            - mysql -uroot -e "GRANT ALL ON meetme.* TO 'meetme'@'localhost';"
            - php artisan migrate --force --seed
    tests:
        override:
            -
                command: 'phpunit --configuration phpunit.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'

